// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9OW65AFfudUPlJJpuy5gUaIHkvWcOCGA',
    appId: '1:368654862186:web:c15a6ac4d6e42490f48713',
    messagingSenderId: '368654862186',
    projectId: 'framy-app',
    authDomain: 'framy-app.firebaseapp.com',
    storageBucket: 'framy-app.firebasestorage.app',
    measurementId: 'G-HVTQX0Y11K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF3_AygpnvYlAejVC-2Tv8DkcfZNbDvpk',
    appId: '1:368654862186:android:a4ecf49bce755af7f48713',
    messagingSenderId: '368654862186',
    projectId: 'framy-app',
    storageBucket: 'framy-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9OW65AFfudUPlJJpuy5gUaIHkvWcOCGA',
    appId: '1:368654862186:web:dc29d19aa54c67b7f48713',
    messagingSenderId: '368654862186',
    projectId: 'framy-app',
    authDomain: 'framy-app.firebaseapp.com',
    storageBucket: 'framy-app.firebasestorage.app',
    measurementId: 'G-TKVH7EQH1P',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCtqKAHmNuha1cmePxmMLnqMYiTF81LrI',
    appId: '1:368654862186:ios:cde22147b8977a81f48713',
    messagingSenderId: '368654862186',
    projectId: 'framy-app',
    storageBucket: 'framy-app.firebasestorage.app',
    iosBundleId: 'com.example.mobile2project1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCtqKAHmNuha1cmePxmMLnqMYiTF81LrI',
    appId: '1:368654862186:ios:cde22147b8977a81f48713',
    messagingSenderId: '368654862186',
    projectId: 'framy-app',
    storageBucket: 'framy-app.firebasestorage.app',
    iosBundleId: 'com.example.mobile2project1',
  );
}
